### ISSUE TITLE
What was the assignment?

### ISSUE THREAD

**Issue by amakukha** [dushyantbehl/less#1]
> Simple assignment on Unix command "less" asked in a programming interview

So, what was the assignment if I may ask?

**Comment by dushyantbehl** [comment]
The assignment was to use the source code of less (version 451) and make change to it so that any emoji in the text input passed to less in the form of ':-)' or ':-(' would be shown in unicode characters like 😄 or 😞 
Also to add a unit test for any function you might add.
Added this to the repo description.
